-- Seed Data for Volunteer Opportunities Hub
-- Indian Organizations and Sample Data

-- Insert Badges
INSERT INTO badges (name, description, icon_url, category, requirement_type, requirement_value, color) VALUES
('First Step', 'Completed your first volunteer opportunity', '🎯', 'milestone', 'opportunities', 1, '#10B981'),
('Dedicated Volunteer', 'Completed 5 volunteer opportunities', '⭐', 'milestone', 'opportunities', 5, '#F59E0B'),
('Community Champion', 'Completed 10 volunteer opportunities', '🏆', 'milestone', 'opportunities', 10, '#8B5CF6'),
('Time Giver', 'Contributed 10+ hours of volunteering', '⏰', 'hours', 'hours', 10, '#3B82F6'),
('Century Club', 'Contributed 100+ hours of volunteering', '💎', 'hours', 'hours', 100, '#EC4899'),
('Early Bird', 'Applied to an opportunity within 24 hours of posting', '🌅', 'special', 'special', 1, '#FBBF24'),
('Social Butterfly', 'Volunteered in 5 different categories', '🦋', 'variety', 'categories', 5, '#14B8A6'),
('Team Player', 'Completed a group volunteering opportunity', '🤝', 'collaboration', 'special', 1, '#6366F1'),
('Environment Warrior', 'Completed 3 environmental volunteering opportunities', '🌱', 'category', 'environment', 3, '#22C55E'),
('Education Hero', 'Completed 3 education-related volunteering opportunities', '📚', 'category', 'education', 3, '#0EA5E9');

-- Insert Organizations (Indian)
INSERT INTO organizations (name, description, logo_url, banner_url, website, email, phone, address, city, state, country, latitude, longitude, category, subcategories, founded_year, team_size, mission, vision, is_verified, rating, total_reviews) VALUES
('Teach For India', 'A movement of leaders working to eliminate educational inequity in India by placing fellows in low-income schools.', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=150', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800', 'https://www.teachforindia.org', 'info@teachforindia.org', '+91-22-61546000', 'Teach For India, 402, A-Wing, Solitaire Corporate Park, Chakala, Andheri (Kurla Road)', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8845, 'Education', ARRAY['Teaching', 'Mentoring', 'Youth Development'], 2009, 500, 'To create a movement of leaders who will eliminate educational inequity.', 'An India where all children get an excellent education.', TRUE, 4.8, 1250),

('CRY - Child Rights and You', 'An Indian non-profit that believes in every child''s right to a childhood - to live, learn, grow and play.', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=150', 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800', 'https://www.cry.org', 'info@crymail.org', '+91-33-22894000', 'CRY, 15A, Dr. Rajendra Prasad Sarani, 1st Floor', 'Kolkata', 'West Bengal', 'India', 22.5726, 88.3639, 'Child Welfare', ARRAY['Child Rights', 'Education', 'Healthcare'], 1979, 300, 'To enable people to take responsibility for the situation of the deprived Indian child.', 'A happy, healthy, and creative child whose rights are protected and honored.', TRUE, 4.7, 980),

('WWF India', 'The Indian part of the World Wide Fund for Nature, working on wildlife conservation and environmental protection.', 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=150', 'https://images.unsplash.com/photo-1448375240586-dfd8d395ea6c?w=800', 'https://www.wwfindia.org', 'contact@wwfindia.net', '+91-11-41504700', 'WWF-India, 172 B, Lodhi Estate, New Delhi', 'New Delhi', 'Delhi', 'India', 28.6139, 77.2090, 'Environment', ARRAY['Wildlife Conservation', 'Environmental Protection', 'Climate Change'], 1969, 400, 'To stop the degradation of the planet''s natural environment and build a future in which humans live in harmony with nature.', 'A world where people and nature thrive.', TRUE, 4.6, 850),

('HelpAge India', 'Working for the cause and care of disadvantaged older persons to improve their quality of life.', 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150', 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=800', 'https://www.helpageindia.org', 'info@helpageindia.org', '+91-11-41688000', 'HelpAge India, C-14, Qutab Institutional Area, New Delhi', 'New Delhi', 'Delhi', 'India', 28.5450, 77.1630, 'Elderly Care', ARRAY['Elderly Care', 'Healthcare', 'Social Support'], 1978, 250, 'To work for the cause and care of disadvantaged older persons and improve their quality of life.', 'A society where elderly people live with dignity and respect.', TRUE, 4.5, 720),

('Make A Difference (MAD)', 'A youth volunteer network that works with children in orphanages and street shelters.', 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=150', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800', 'https://www.makeadiff.in', 'info@makeadiff.in', '+91-484-2388222', 'Make A Difference, 3rd Floor, Kavitha Building, Kaloor', 'Kochi', 'Kerala', 'India', 9.9312, 76.2673, 'Youth Development', ARRAY['Youth Mentoring', 'Education', 'Child Welfare'], 2006, 200, 'To ensure that children living in shelter homes get the support and care they need.', 'A world where every child has equal opportunities.', TRUE, 4.7, 640),

('Goonj', 'An award-winning social enterprise working on clothing as a basic but unaddressed need.', 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=150', 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800', 'https://www.goonj.org', 'info@goonj.org', '+91-11-41415575', 'Goonj, J-93, Sarita Vihar, New Delhi', 'New Delhi', 'Delhi', 'India', 28.5355, 77.2890, 'Social Welfare', ARRAY['Clothing', 'Disaster Relief', 'Rural Development'], 1999, 350, 'To address the basic but ignored needs of people.', 'A world where everyone''s basic needs are met with dignity.', TRUE, 4.8, 890),

('Samarthanam Trust', 'Working for the empowerment of persons with disabilities and the underprivileged.', 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=150', 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800', 'https://www.samarthanam.org', 'info@samarthanam.org', '+91-80-26592999', 'Samarthanam Trust, #112, 2nd Floor, 100ft Road, Indiranagar', 'Bangalore', 'Karnataka', 'India', 12.9716, 77.5946, 'Disability Support', ARRAY['Disability Rights', 'Education', 'Employment'], 1997, 180, 'To empower persons with disabilities and the underprivileged through education, training, and employment.', 'An inclusive society where everyone has equal opportunities.', TRUE, 4.6, 560),

('Rural Development Trust', 'Working for the integrated development of rural communities in India.', 'https://images.unsplash.com/photo-1504384308090-c54be3852f33?w=150', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800', 'https://www.rdt.org.in', 'info@rdt.org.in', '+91-8554-284000', 'RDT, Bathalapalli, Anantapur District', 'Anantapur', 'Andhra Pradesh', 'India', 14.6800, 77.6000, 'Rural Development', ARRAY['Rural Development', 'Healthcare', 'Education'], 1969, 450, 'To facilitate the integrated development of rural communities.', 'Prosperous and self-reliant rural communities.', TRUE, 4.5, 480),

('Pratham Education Foundation', 'One of India''s largest education NGOs, working to provide quality education to underprivileged children.', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=150', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800', 'https://www.pratham.org', 'info@pratham.org', '+91-22-22824444', 'Pratham, 4th Floor, Pratham Centre, Juhu Tara Road', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8296, 'Education', ARRAY['Primary Education', 'Literacy', 'Child Development'], 1995, 600, 'Every child in school and learning well.', 'All children achieve basic reading, writing, and arithmetic skills.', TRUE, 4.9, 1420),

('Snehalaya', 'Working for the rehabilitation and empowerment of women, children, and LGBTQ+ communities.', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800', 'https://www.snehalaya.org', 'info@snehalaya.org', '+91-724-2250000', 'Snehalaya, Ahmednagar, Maharashtra', 'Ahmednagar', 'Maharashtra', 'India', 19.0948, 74.7479, 'Social Welfare', ARRAY['Women Empowerment', 'Child Welfare', 'LGBTQ+ Rights'], 1989, 220, 'To provide shelter, care, and education to women, children, and LGBTQ+ communities in need.', 'A society free from discrimination and violence.', TRUE, 4.7, 670),

('Akshaya Patra Foundation', 'Implementing the Mid-Day Meal Scheme in government schools to fight classroom hunger.', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=150', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800', 'https://www.akshayapatra.org', 'info@akshayapatra.org', '+91-80-30143400', 'Akshaya Patra, 18th Cross, 7th Main, ISRO Layout', 'Bangalore', 'Karnataka', 'India', 12.9716, 77.5946, 'Child Welfare', ARRAY['Child Nutrition', 'Education', 'Food Security'], 2000, 5000, 'No child in India shall be deprived of education because of hunger.', 'A hunger-free and educated India.', TRUE, 4.8, 2100),

('Sightsavers India', 'Working to prevent avoidable blindness and promote equality of opportunity for people with disabilities.', 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=150', 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800', 'https://www.sightsaversindia.in', 'info@sightsavers.org', '+91-44-28192000', 'Sightsavers India, 42, Dr. Radhakrishnan Salai', 'Chennai', 'Tamil Nadu', 'India', 13.0827, 80.2707, 'Healthcare', ARRAY['Eye Care', 'Disability Support', 'Healthcare'], 1966, 300, 'To eliminate avoidable blindness and support people with visual impairments to lead independent lives.', 'A world where no one is blind from avoidable causes.', TRUE, 4.6, 780),

('Udayan Care', 'Working for the rights of children and youth, especially girls, through education and skill development.', 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=150', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800', 'https://www.udayancare.org', 'info@udayancare.org', '+91-11-41415575', 'Udayan Care, C-56, Sector 62, Noida', 'Noida', 'Uttar Pradesh', 'India', 28.5355, 77.3910, 'Child Welfare', ARRAY['Child Education', 'Youth Development', 'Skill Development'], 1994, 150, 'To enable disadvantaged children and youth to become self-reliant.', 'A society where every child has the opportunity to thrive.', TRUE, 4.5, 520),

('Magic Bus India Foundation', 'Using sport as a tool to engage children and ensure they complete their education.', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150', 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800', 'https://www.magicbusindia.org', 'info@magicbusindia.org', '+91-22-61546000', 'Magic Bus, 402, A-Wing, Solitaire Corporate Park', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8845, 'Youth Development', ARRAY['Sports for Development', 'Education', 'Youth Empowerment'], 1999, 400, 'To move children out of poverty through sport and education.', 'A world where every child has the opportunity to succeed.', TRUE, 4.7, 890),

('Smile Foundation', 'An NGO working for the welfare of underprivileged children through education and healthcare.', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=150', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800', 'https://www.smilefoundationindia.org', 'info@smilefoundationindia.org', '+91-11-41688000', 'Smile Foundation, C-14, Qutab Institutional Area', 'New Delhi', 'Delhi', 'India', 28.5450, 77.1630, 'Child Welfare', ARRAY['Child Education', 'Healthcare', 'Skill Development'], 2002, 600, 'To empower underprivileged children through education and healthcare.', 'A world where every child has access to quality education and healthcare.', TRUE, 4.6, 1100),

('SEWA Bharat', 'Self-Employed Women''s Association working for women''s empowerment and economic independence.', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800', 'https://www.sewabharat.org', 'info@sewabharat.org', '+91-79-26571000', 'SEWA Bharat, 12, Navrangpura', 'Ahmedabad', 'Gujarat', 'India', 23.0225, 72.5714, 'Women Empowerment', ARRAY['Women Empowerment', 'Economic Development', 'Skill Training'], 1972, 2000, 'To strengthen the movement of women workers for full employment and self-reliance.', 'A society where women are economically independent and empowered.', TRUE, 4.8, 1800),

('Nanhi Kali', 'Project providing education support to underprivileged girls in India.', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=150', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800', 'https://www.nanhikali.org', 'info@nanhikali.org', '+91-22-61546000', 'Nanhi Kali, 402, A-Wing, Solitaire Corporate Park', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8845, 'Education', ARRAY['Girl Child Education', 'Education', 'Women Empowerment'], 1996, 250, 'To support the education of underprivileged girls in India.', 'An India where every girl has access to quality education.', TRUE, 4.7, 950),

('Rural Litigation and Entitlement Kendra (RLEK)', 'Working for the rights of forest dwellers and tribal communities in Uttarakhand.', 'https://images.unsplash.com/photo-1504384308090-c54be3852f33?w=150', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800', 'https://www.rlek.org', 'info@rlek.org', '+91-135-2654321', 'RLEK, Rajpur Road', 'Dehradun', 'Uttarakhand', 'India', 30.3165, 78.0322, 'Social Welfare', ARRAY['Tribal Rights', 'Forest Rights', 'Legal Aid'], 1969, 120, 'To empower forest dwellers and tribal communities through legal aid and awareness.', 'A society where tribal communities have equal rights and opportunities.', TRUE, 4.4, 380),

('Bharat Petroleum Corporation Limited (BPCL) - CSR', 'Corporate social responsibility initiatives in education, healthcare, and environment.', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150', 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800', 'https://www.bpcl.in', 'csr@bpcl.in', '+91-22-61546000', 'BPCL, Ballard Estate', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8845, 'Corporate Social Responsibility', ARRAY['Education', 'Healthcare', 'Environment'], 1976, 500, 'To contribute to nation-building through sustainable social initiatives.', 'A developed and inclusive India.', TRUE, 4.5, 670),

('Tata Trusts', 'Philanthropic organization working in health, education, and livelihood sectors.', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=150', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800', 'https://www.tatatrusts.org', 'info@tatatrusts.org', '+91-22-66658000', 'Tata Trusts, Bombay House', 'Mumbai', 'Maharashtra', 'India', 19.1156, 72.8845, 'Philanthropy', ARRAY['Healthcare', 'Education', 'Livelihood'], 1892, 1000, 'To improve the quality of life of communities through sustainable development initiatives.', 'A prosperous and equitable India.', TRUE, 4.9, 2500);

-- Insert Opportunities
INSERT INTO opportunities (organization_id, title, description, requirements, responsibilities, skills_required, category, subcategory, location, city, state, country, is_remote, latitude, longitude, time_commitment, duration, start_date, end_date, deadline, positions_available, positions_filled, min_age, benefits, status) VALUES
-- Education Opportunities
((SELECT id FROM organizations WHERE name = 'Teach For India'), 'Teaching Fellow', 'Teach underprivileged children in low-income schools and make a real impact on their lives.', ARRAY['Bachelor''s degree', 'Fluency in English and local language', 'Commitment to 2 years'], ARRAY['Plan and deliver lessons', 'Assess student progress', 'Engage with parents', 'Participate in training programs'], ARRAY['Teaching', 'Communication', 'Leadership', 'Patience'], 'Education', 'Teaching', 'Multiple locations across India', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8845, 'Full-time', '2 years', '2024-03-01', '2026-03-01', '2024-02-15', 50, 25, 21, ARRAY['Stipend of ₹30,000/month', 'Professional development', 'Leadership training', 'Networking opportunities'], 'active'),

((SELECT id FROM organizations WHERE name = 'Pratham Education Foundation'), 'Literacy Volunteer', 'Help children improve their reading and writing skills through one-on-one tutoring sessions.', ARRAY['Basic education', 'Patience with children', 'Weekend availability'], ARRAY['Conduct reading sessions', 'Assess literacy levels', 'Track progress', 'Prepare learning materials'], ARRAY['Teaching', 'Patience', 'Communication'], 'Education', 'Literacy', 'Community centers in Mumbai', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8296, '4 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-25', 30, 15, 18, ARRAY['Certificate of appreciation', 'Teaching experience', 'Community impact'], 'active'),

((SELECT id FROM organizations WHERE name = 'Akshaya Patra Foundation'), 'Mid-Day Meal Volunteer', 'Help serve nutritious meals to school children and support the mid-day meal program.', ARRAY['Passion for child welfare', 'Physical fitness', 'Team player'], ARRAY['Assist in meal preparation', 'Serve meals to children', 'Maintain hygiene standards', 'Track meal distribution'], ARRAY['Teamwork', 'Communication', 'Food Safety'], 'Child Welfare', 'Child Nutrition', 'Government schools in Bangalore', 'Bangalore', 'Karnataka', 'India', FALSE, 12.9716, 77.5946, '4 hours/day', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 40, 20, 18, ARRAY['Certificate', 'Community service', 'Making a difference'], 'active'),

((SELECT id FROM organizations WHERE name = 'Nanhi Kali'), 'Girl Child Education Mentor', 'Mentor underprivileged girls and support their education journey.', ARRAY['Passion for girls'' education', 'Patience and empathy', 'Weekend availability'], ARRAY['Conduct mentoring sessions', 'Help with homework', 'Provide career guidance', 'Track academic progress'], ARRAY['Mentoring', 'Communication', 'Empathy'], 'Education', 'Girl Child Education', 'Community centers across India', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8845, '4 hours/week', '1 year', '2024-02-01', '2025-02-01', '2024-01-25', 50, 25, 20, ARRAY['Mentorship training', 'Certificate', 'Empowering girls'], 'active'),

-- Environment Opportunities
((SELECT id FROM organizations WHERE name = 'WWF India'), 'Wildlife Conservation Volunteer', 'Participate in wildlife conservation projects and awareness campaigns across India.', ARRAY['Interest in wildlife conservation', 'Physical fitness', 'Willingness to travel'], ARRAY['Field surveys', 'Data collection', 'Community awareness', 'Report writing'], ARRAY['Research', 'Communication', 'Field work'], 'Environment', 'Wildlife Conservation', 'Various national parks and sanctuaries', 'New Delhi', 'Delhi', 'India', FALSE, 28.6139, 77.2090, 'Flexible', '3 months', '2024-02-15', '2024-05-15', '2024-02-01', 20, 8, 20, ARRAY['Field experience', 'Conservation training', 'Networking with experts'], 'active'),

((SELECT id FROM organizations WHERE name = 'WWF India'), 'Climate Action Campaigner', 'Raise awareness about climate change and organize community action programs.', ARRAY['Knowledge of climate issues', 'Public speaking skills', 'Social media savvy'], ARRAY['Organize awareness events', 'Manage social media campaigns', 'Engage with communities', 'Create educational content'], ARRAY['Communication', 'Social Media', 'Event Management'], 'Environment', 'Climate Change', 'Remote with field visits', 'New Delhi', 'Delhi', 'India', TRUE, 28.6139, 77.2090, '10 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 15, 5, 18, ARRAY['Campaign experience', 'Certificate', 'Networking'], 'active'),

-- Child Welfare Opportunities
((SELECT id FROM organizations WHERE name = 'CRY'), 'Child Rights Advocate', 'Advocate for children''s rights and help implement child protection programs.', ARRAY['Background in social work', 'Understanding of child rights', 'Good communication skills'], ARRAY['Conduct awareness programs', 'Document cases', 'Liaise with authorities', 'Support families'], ARRAY['Advocacy', 'Communication', 'Social Work'], 'Child Welfare', 'Child Rights', 'Kolkata and surrounding areas', 'Kolkata', 'West Bengal', 'India', FALSE, 22.5726, 88.3639, '20 hours/week', '1 year', '2024-03-01', '2025-03-01', '2024-02-20', 10, 4, 21, ARRAY['Training in child rights', 'Field experience', 'Certificate'], 'active'),

((SELECT id FROM organizations WHERE name = 'Smile Foundation'), 'Healthcare Volunteer for Children', 'Support healthcare initiatives for underprivileged children.', ARRAY['Background in healthcare (preferred)', 'Empathy for children', 'Basic medical knowledge'], ARRAY['Assist in health camps', 'Provide health education', 'Support medical teams', 'Track health records'], ARRAY['Healthcare', 'Communication', 'Empathy'], 'Healthcare', 'Child Healthcare', 'Community health centers', 'New Delhi', 'Delhi', 'India', FALSE, 28.5450, 77.1630, '8 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 25, 10, 20, ARRAY['Healthcare experience', 'Certificate', 'Making a difference'], 'active'),

((SELECT id FROM organizations WHERE name = 'Udayan Care'), 'Youth Mentor', 'Mentor children living in shelter homes and help them with education and life skills.', ARRAY['Patience and empathy', 'Weekend availability', 'Background check clearance'], ARRAY['Weekly mentoring sessions', 'Academic support', 'Life skills training', 'Emotional support'], ARRAY['Mentoring', 'Communication', 'Empathy'], 'Youth Development', 'Mentoring', 'Shelter homes in Noida', 'Noida', 'Uttar Pradesh', 'India', FALSE, 28.5355, 77.3910, '4 hours/weekend', '1 year', '2024-02-01', '2025-02-01', '2024-01-25', 25, 12, 20, ARRAY['Mentorship training', 'Personal growth', 'Making a difference'], 'active'),

((SELECT id FROM organizations WHERE name = 'Magic Bus India Foundation'), 'Sports Coach', 'Use sports as a tool to engage children and ensure they complete their education.', ARRAY['Interest in sports', 'Experience working with children', 'Physical fitness'], ARRAY['Conduct sports sessions', 'Teach life skills through sports', 'Track attendance', 'Engage with parents'], ARRAY['Sports', 'Communication', 'Leadership'], 'Youth Development', 'Sports for Development', 'Community centers in Mumbai', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8845, '6 hours/week', '1 year', '2024-02-01', '2025-02-01', '2024-01-20', 30, 15, 18, ARRAY['Sports training', 'Certificate', 'Impact through sports'], 'active'),

-- Elderly Care Opportunities
((SELECT id FROM organizations WHERE name = 'HelpAge India'), 'Elderly Care Companion', 'Spend time with elderly citizens, help them with daily tasks, and provide companionship.', ARRAY['Patience and empathy', 'Respect for elders', 'Basic first aid knowledge'], ARRAY['Visit elderly at home', 'Assist with daily tasks', 'Provide companionship', 'Organize activities'], ARRAY['Empathy', 'Communication', 'Patience'], 'Elderly Care', 'Companionship', 'Senior citizen homes in Delhi', 'New Delhi', 'Delhi', 'India', FALSE, 28.5450, 77.1630, '5 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 40, 18, 18, ARRAY['Training in elderly care', 'Certificate', 'Community service'], 'active'),

-- Social Welfare Opportunities
((SELECT id FROM organizations WHERE name = 'Goonj'), 'Clothing Drive Volunteer', 'Organize clothing collection drives and help sort and distribute clothes to those in need.', ARRAY['Organizational skills', 'Physical ability to lift boxes', 'Team player'], ARRAY['Organize collection drives', 'Sort and pack clothes', 'Coordinate distribution', 'Maintain records'], ARRAY['Organization', 'Teamwork', 'Communication'], 'Social Welfare', 'Clothing', 'Delhi NCR', 'New Delhi', 'Delhi', 'India', FALSE, 28.5355, 77.2890, '8 hours/week', '3 months', '2024-02-01', '2024-05-01', '2024-01-25', 30, 10, 18, ARRAY['Community service experience', 'Certificate', 'Networking'], 'active'),

((SELECT id FROM organizations WHERE name = 'SEWA Bharat'), 'Women Empowerment Volunteer', 'Support women''s economic empowerment through skill training and microfinance.', ARRAY['Understanding of women''s issues', 'Basic financial literacy', 'Communication skills'], ARRAY['Conduct skill training workshops', 'Support microfinance groups', 'Provide business guidance', 'Track progress'], ARRAY['Training', 'Communication', 'Financial Literacy'], 'Women Empowerment', 'Economic Development', 'Community centers in Ahmedabad', 'Ahmedabad', 'Gujarat', 'India', FALSE, 23.0225, 72.5714, '10 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 20, 8, 21, ARRAY['Training experience', 'Certificate', 'Empowering women'], 'active'),

-- Disability Support Opportunities
((SELECT id FROM organizations WHERE name = 'Samarthanam Trust'), 'Disability Support Volunteer', 'Assist persons with disabilities in their daily activities and help them access resources.', ARRAY['Understanding of disability issues', 'Patience and empathy', 'Basic sign language (preferred)'], ARRAY['Assist with daily activities', 'Help access resources', 'Provide companionship', 'Organize events'], ARRAY['Empathy', 'Communication', 'Patience'], 'Disability Support', 'Daily Living Support', 'Bangalore', 'Bangalore', 'Karnataka', 'India', FALSE, 12.9716, 77.5946, '6 hours/week', '6 months', '2024-02-15', '2024-08-15', '2024-02-01', 20, 7, 20, ARRAY['Disability awareness training', 'Certificate', 'Meaningful work'], 'active'),

((SELECT id FROM organizations WHERE name = 'Sightsavers India'), 'Eye Care Volunteer', 'Support eye care initiatives and help prevent avoidable blindness.', ARRAY['Interest in healthcare', 'Good communication skills', 'Willingness to travel'], ARRAY['Assist in eye screening camps', 'Provide health education', 'Support medical teams', 'Track patient records'], ARRAY['Healthcare', 'Communication', 'Empathy'], 'Healthcare', 'Eye Care', 'Eye care centers in Chennai', 'Chennai', 'Tamil Nadu', 'India', FALSE, 13.0827, 80.2707, '8 hours/week', '3 months', '2024-02-01', '2024-05-01', '2024-01-20', 25, 10, 20, ARRAY['Healthcare experience', 'Certificate', 'Preventing blindness'], 'active'),

-- Rural Development Opportunities
((SELECT id FROM organizations WHERE name = 'Rural Development Trust'), 'Rural Healthcare Volunteer', 'Support healthcare initiatives in rural communities and assist medical teams.', ARRAY['Background in healthcare (preferred)', 'Willingness to work in rural areas', 'Basic medical knowledge'], ARRAY['Assist medical teams', 'Conduct health camps', 'Health education', 'Data collection'], ARRAY['Healthcare', 'Communication', 'Adaptability'], 'Healthcare', 'Rural Healthcare', 'Anantapur district', 'Anantapur', 'Andhra Pradesh', 'India', FALSE, 14.6800, 77.6000, 'Full-time', '6 months', '2024-03-01', '2024-09-01', '2024-02-15', 15, 6, 21, ARRAY['Healthcare experience', 'Rural exposure', 'Certificate'], 'active'),

((SELECT id FROM organizations WHERE name = 'Rural Litigation and Entitlement Kendra (RLEK)'), 'Tribal Rights Advocate', 'Advocate for the rights of forest dwellers and tribal communities.', ARRAY['Background in law or social work', 'Understanding of tribal rights', 'Good communication skills'], ARRAY['Conduct legal awareness programs', 'Document cases', 'Liaise with authorities', 'Support communities'], ARRAY['Legal Knowledge', 'Communication', 'Advocacy'], 'Social Welfare', 'Tribal Rights', 'Uttarakhand tribal areas', 'Dehradun', 'Uttarakhand', 'India', FALSE, 30.3165, 78.0322, '20 hours/week', '1 year', '2024-02-01', '2025-02-01', '2024-01-20', 10, 4, 21, ARRAY['Legal experience', 'Certificate', 'Social impact'], 'active'),

-- Women Empowerment Opportunities
((SELECT id FROM organizations WHERE name = 'Snehalaya'), 'Women Empowerment Volunteer', 'Support women in need through counseling, skill development, and legal assistance.', ARRAY['Understanding of women''s issues', 'Counseling skills (preferred)', 'Empathy and patience'], ARRAY['Counseling sessions', 'Skill development workshops', 'Legal assistance support', 'Awareness programs'], ARRAY['Counseling', 'Communication', 'Empathy'], 'Social Welfare', 'Women Empowerment', 'Ahmednagar', 'Ahmednagar', 'Maharashtra', 'India', FALSE, 19.0948, 74.7479, '15 hours/week', '1 year', '2024-02-01', '2025-02-01', '2024-01-20', 12, 5, 21, ARRAY['Counseling training', 'Social work experience', 'Certificate'], 'active'),

-- Corporate Social Responsibility
((SELECT id FROM organizations WHERE name = 'Bharat Petroleum Corporation Limited (BPCL) - CSR'), 'CSR Initiative Volunteer', 'Support BPCL''s corporate social responsibility initiatives in education and environment.', ARRAY['Interest in CSR activities', 'Good communication skills', 'Team player'], ARRAY['Organize CSR events', 'Support education programs', 'Environmental initiatives', 'Track impact'], ARRAY['Communication', 'Organization', 'Teamwork'], 'Corporate Social Responsibility', 'Education', 'Mumbai and surrounding areas', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8845, '8 hours/week', '6 months', '2024-02-01', '2024-08-01', '2024-01-20', 20, 8, 20, ARRAY['Corporate experience', 'Certificate', 'Networking'], 'active'),

-- Philanthropy
((SELECT id FROM organizations WHERE name = 'Tata Trusts'), 'Philanthropy Program Volunteer', 'Support Tata Trusts'' philanthropic initiatives in health, education, and livelihood.', ARRAY['Interest in philanthropy', 'Good communication skills', 'Analytical thinking'], ARRAY['Support program implementation', 'Data collection and analysis', 'Stakeholder engagement', 'Report writing'], ARRAY['Communication', 'Analysis', 'Program Management'], 'Philanthropy', 'Healthcare', 'Mumbai', 'Mumbai', 'Maharashtra', 'India', FALSE, 19.1156, 72.8845, '10 hours/week', '1 year', '2024-02-01', '2025-02-01', '2024-01-20', 15, 6, 21, ARRAY['Philanthropy experience', 'Certificate', 'Social impact'], 'active');

-- Insert Demo User
INSERT INTO users (email, password, full_name, phone, avatar_url, bio, location, skills, interests, total_hours, total_opportunities, is_verified) VALUES
('demo@volunteerhub.com', '$2a$10$rK9J8z8z8z8z8z8z8z8zeExampleHashedPassword12345678901234567890', 'Priya Sharma', '+91-9876543210', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200', 'Passionate about making a difference in my community. Love working with children and environmental causes. Experienced volunteer with 45+ hours of service.', 'Mumbai, Maharashtra', ARRAY['Teaching', 'Communication', 'Event Planning', 'Social Media', 'Mentoring'], ARRAY['Education', 'Environment', 'Child Welfare', 'Youth Development', 'Women Empowerment'], 45, 8, TRUE);

-- Insert Demo User Applications
INSERT INTO applications (user_id, opportunity_id, organization_id, status, cover_letter, motivation, availability) VALUES
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Literacy Volunteer'), (SELECT id FROM organizations WHERE name = 'Pratham Education Foundation'), 'accepted', 'I am passionate about education and believe every child deserves quality education. I have experience tutoring children and would love to contribute to this noble cause.', 'I want to make a real difference in children''s lives by helping them develop essential literacy skills.', 'Weekends, 4 hours per week'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), (SELECT id FROM organizations WHERE name = 'WWF India'), 'in_progress', 'Climate change is one of the most pressing issues of our time. I have experience in social media management and want to use my skills to raise awareness.', 'I believe in the power of collective action and want to mobilize communities to take climate action.', 'Flexible, 10 hours per week'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Youth Mentor'), (SELECT id FROM organizations WHERE name = 'Make A Difference (MAD)'), 'pending', 'I have always been passionate about youth development and believe in the power of mentorship. I want to guide and inspire young minds.', 'Every child deserves a mentor who believes in them. I want to be that person.', 'Weekends, 4 hours per session');

-- Insert Demo User Progress
INSERT INTO user_progress (user_id, opportunity_id, organization_id, hours_contributed, tasks_completed, start_date, end_date, status, feedback, rating) VALUES
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Literacy Volunteer'), (SELECT id FROM organizations WHERE name = 'Pratham Education Foundation'), 25.5, 15, '2024-01-15', '2024-02-15', 'completed', 'Excellent dedication and patience with children. The students showed significant improvement under her guidance.', 5),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), (SELECT id FROM organizations WHERE name = 'WWF India'), 12.0, 8, '2024-01-20', NULL, 'in_progress', NULL, NULL),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM opportunities WHERE title = 'Elderly Care Companion'), (SELECT id FROM organizations WHERE name = 'HelpAge India'), 7.5, 5, '2024-01-10', '2024-01-25', 'completed', 'Very compassionate and caring. The elderly residents loved her company.', 5);

-- Insert Demo User Badges
INSERT INTO user_badges (user_id, badge_id) VALUES
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM badges WHERE name = 'First Step')),
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM badges WHERE name = 'Dedicated Volunteer')),
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM badges WHERE name = 'Time Giver')),
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM badges WHERE name = 'Education Hero'));

-- Insert Demo User Daily Schedules
INSERT INTO daily_schedules (user_id, date, opportunity_id, task_title, task_description, start_time, end_time, status, notes) VALUES
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-01', (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), 'Social Media Campaign Planning', 'Plan and schedule posts for the week', '09:00:00', '11:00:00', 'completed', 'Created content calendar for the week'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-02', (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), 'Community Outreach Event', 'Organize awareness event at local college', '14:00:00', '17:00:00', 'completed', 'Successfully engaged 50+ students'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-03', (SELECT id FROM opportunities WHERE title = 'Literacy Volunteer'), 'Reading Session', 'Conduct reading session with children', '10:00:00', '12:00:00', 'completed', 'Children showed great progress'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-04', NULL, 'Volunteer Meeting', 'Monthly volunteer coordination meeting', '16:00:00', '17:30:00', 'scheduled', 'Discuss upcoming opportunities'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-05', (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), 'Content Creation', 'Create educational content on climate change', '09:00:00', '12:00:00', 'scheduled', 'Focus on local climate issues'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-06', (SELECT id FROM opportunities WHERE title = 'Literacy Volunteer'), 'Assessment Day', 'Assess children''s reading progress', '10:00:00', '12:00:00', 'scheduled', 'Prepare progress reports'),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), '2024-02-07', NULL, 'Self Development', 'Online course on NGO management', '19:00:00', '21:00:00', 'scheduled', 'Module 3: Fundraising strategies');

-- Insert Reviews
INSERT INTO reviews (user_id, organization_id, opportunity_id, rating, review_text, is_anonymous) VALUES
((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM organizations WHERE name = 'Pratham Education Foundation'), (SELECT id FROM opportunities WHERE title = 'Literacy Volunteer'), 5, 'Amazing experience! The team at Pratham is incredibly supportive and the work they do is truly impactful. I saw real progress in the children I worked with.', FALSE),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM organizations WHERE name = 'HelpAge India'), (SELECT id FROM opportunities WHERE title = 'Elderly Care Companion'), 5, 'Heartwarming experience. Spending time with the elderly residents taught me so much about life and patience. The organization is well-managed and truly cares for the elderly.', FALSE),

((SELECT id FROM users WHERE email = 'demo@volunteerhub.com'), (SELECT id FROM organizations WHERE name = 'WWF India'), (SELECT id FROM opportunities WHERE title = 'Climate Action Campaigner'), 4, 'Great opportunity to work on climate action. The team is passionate and the campaigns are well-organized. Looking forward to continuing my work with them.', FALSE);